services:
  item-service:
    build: ./item-service
    container_name: item-service
    ports:
      - "9001:9001"

  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - "9002:9002"

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    ports:
      - "9003:9003"

  menu-service:
    build: ./menu-service
    container_name: menu-service
    ports:
      - "9004:9004"

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "9005:9005"

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "9006:9006"

  review-service:
    build: ./review-service
    container_name: review-service
    ports:
      - "9007:9007"